### ISSUE TITLE
link to app throws an error

### ISSUE THREAD

**Issue by iemwill** [melonproject-archive/monitoring#5]
When i check out https://melon-subgraph.now.sh/ this is happening:

The whole page is white and in the middle is this errormessage:
`An unexpected error has occurred.`

Reproduce: Click here https://melon-subgraph.now.sh/

**Comment by iherger** [comment]
Thanks. That's a domain that we used a long time ago.

The correct domain is https://monitoring.melon.network

We will remove the outdated link from the repo description.
